# **PHẦN 1: TIỀN XỬ LÝ VÀ DỌN DẸP DỮ LIỆU**
## **1. Định nghĩa vấn đề**
+ **Mô tả**:
   - Phát hiện và phân loại mã độc trên các thiết bị di động Android bằng tập dữ liệu Android Malware Detection.
   - Dữ liệu ban đầu bao gồm 1 file (Android_Malware.csv)
   - Link tập dữ liệu: https://www.kaggle.com/datasets/subhajournal/android-malware-detection

+ **Mục tiêu**:
   - Xem thông tin chung, kiểm tra tính toàn vẹn và xử lý các giá trị thiếu cho dữ liệu.

## **2. Chuẩn bị vấn đề**

### 2.1. Import các thư viện cần thiết

In [25]:
import pandas as pd
import numpy as np
import pyarrow

pd.set_option("display.max_columns", 500)
pd.set_option("display.max_rows", 500)

### 2.2. Đọc dữ liệu từ file csv

In [26]:
dataFrame = pd.read_csv("../../data/Android_Malware.csv", low_memory=False, skipinitialspace=True)
dataFrame.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,172.217.6.202-10.42.0.211-443-50004-6,10.42.0.211,50004,172.217.6.202,443.0,6.0,13/06/2017 11:52:39,37027,1,1,0.0,0.0,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,54.014638,3.702700e+04,0.000000e+00,37027.0,37027.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0,0,32,32,27.007319,27.007319,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0,1.0,0,0.0,1.0,0.000000,0.000,0.000000,32.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2994.0,362.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
1,1,172.217.6.202-10.42.0.211-443-35455-6,10.42.0.211,35455,172.217.6.202,443.0,6.0,13/06/2017 11:52:39,36653,1,1,0.0,0.0,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,54.565793,3.665300e+04,0.000000e+00,36653.0,36653.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0,0,32,32,27.282896,27.282896,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0,1.0,0,0.0,1.0,0.000000,0.000,0.000000,32.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2860.0,362.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
2,2,131.253.61.68-10.42.0.211-443-51775-6,10.42.0.211,51775,131.253.61.68,443.0,6.0,13/06/2017 11:52:42,534099,8,12,1011.0,11924.0,581.0,0.0,126.375,207.799311,1460.0,0.0,993.666667,656.474376,24218.356522,37.446241,2.811047e+04,4.314810e+04,158676.0,8.0,481340.0,6.876286e+04,6.237618e+04,158676.0,449.0,487990.0,44362.727273,86342.042540,217790.0,8.0,0.0,0.0,0,0,180,244,14.978496,22.467745,0.0,1460.0,615.952381,672.744786,452585.547619,0.0,0.0,0.0,1.0,0.0,0.0,0,0.0,1.0,646.750000,126.375,993.666667,180.0,0,0.0,0.0,0.0,0.0,0.0,8.0,1011.0,12.0,11924.0,65535.0,63441.0,3.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
3,3,131.253.61.68-10.42.0.211-443-51775-6,10.42.0.211,51775,131.253.61.68,443.0,6.0,13/06/2017 11:52:43,9309,3,0,0.0,0.0,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,322.268772,4.654500e+03,5.137131e+03,8287.0,1022.0,9309.0,4.654500e+03,5.137131e+03,8287.0,1022.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0,0,60,0,322.268772,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0,0.0,0.0,0.000000,0.000,0.000000,60.0,0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,65535.0,-1.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
4,4,131.253.61.68-10.42.0.211-443-51776-6,10.42.0.211,51776,131.253.61.68,443.0,6.0,13/06/2017 11:52:42,19890496,8,6,430.0,5679.0,218.0,0.0,53.750,99.538578,1460.0,0.0,946.500000,710.412204,307.131607,0.703854,1.530038e+06,5.377887e+06,19426714.0,7.0,19890496.0,2.841499e+06,7.314093e+06,19426714.0,639.0,410964.0,82192.800000,154845.683018,355945.0,7.0,0.0,0.0,0,0,180,124,0.402202,0.301652,0.0,1460.0,407.266667,626.958471,393076.923810,0.0,0.0,0.0,1.0,0.0,0.0,0,0.0,0.0,436.357143,53.750,946.500000,180.0,0,0.0,0.0,0.0,0.0,0.0,8.0,430.0,6.0,5679.0,65535.0,64022.0,2.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware

### 2.3. Liệt kê các thông tin cơ bản của dữ liệu

In [27]:
dataFrame.describe()

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,ECE Flag Count,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,355630.000000,3.556300e+05,3.556300e+05,355630.000000,3.556300e+05,355630.000000,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,355630.000000,355630.000000,355630.000000,355630.000000,355630.000000,355630.000000,355630.000000,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,3.556300e+05,355630.000000,355630.000000,355630.000000,355630.000000,3.556300e+05,3.556300e+05,3.556300e+05,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355629.000000,355628.0,355627.000000,355627.000000,355627.000000,3.556270e+05,355626.0,355626.0,355626.0,355626.0,355626.0,355626.000000,3.556260e+05,355626.000000,3.556260e+05,355626.000000,355626.000000,355626.000000,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05
mean,1945.719231,3.914129e+04,5.202541e+03,9.765190,1.092975e+07,7.433718,1.420368e+01,6.796042e+02,1.129508e+04,2.150150e+02,12.520248,59.643539,79.525507,320.407568,23.058444,168.537728,124.385048,8.398908e+04,5.494580e+03,3.175805e+06,2.426805e+06,9.448524e+06,2.057882e+06,7.539937e+06,3.206486e+06,1.934125e+06,6.253269e+06,2.079831e+06,5.632427e+06,9.461561e+05,1.407295e+06,4.709261e+06,3.426198e+05,0.067356,0.000541,0.002463,0.000337,-7.601258e+05,-1.580857e+06,4.685509e+03,814.880376,8.506264,374.613656,115.158037,144.897877,71484.125420,0.041301,0.249721,0.000357,0.331337,0.431017,0.204120,0.0,127.433046,59.643950,168.536774,-7.601322e+05,0.0,0.0,0.0,0.0,0.0,7.357412,6.791997e+02,10.494593,1.129421e+04,23386.883271,2032.585548,1.524405,-2.831850e+04,1.628143e+05,2.195225e+04,1.851564e+05,1.456534e+05,4.025724e+06,3.182527e+05,4.304876e+06,3.779037e+06
std,1840.477646,1.794632e+04,1.452135e+04,750.541237,2.180861e+07,81.015658,2.220247e+03,1.942007e+04,2.763871e+05,1.834912e+03,58.296263,119.309000,154.228290,540.178699,59.010184,311.332303,585.875853,9.112698e+05,3.913503e+04,8.459869e+06,6.202456e+06,1.829193e+07,7.922416e+06,1.843187e+07,8.859162e+06,6.110693e+06,1.447375e+07,8.166472e+06,1.816008e+07,4.583215e+06,5.227275e+06,1.517925e+07,3.750278e+06,1.167848,0.322799,1.468943,0.188289,2.090455e+08,4.385654e+08,3.625912e+04,8590.913666,58.917594,563.916123,193.966724,224.701001,137221.726917,14.689980,109.894355,0.212963,0.470695,0.496297,0.403058,0.0,199.981350,119.309412,311.332884,2.090464e+08,0.0,0.0,0.0,0.0,0.0,67.005199,1.941864e+04,191.679025,2.763881e+05,30744.982569,8532.735513,14.938322,5.543875e+06,8.817765e+05,2.860244e+05,1.019477e+06,8.423659e+05,1.441518e+07,2.882901e+06,1.514008e+07,1.407042e+07
min,0.000000,0.000000e+00,0.000000e+00,0.000000,-1.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,-2.000000e+06,-1.000000e+00,0.000000e+00,-1.000000e+00,-4.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-7.533332e+10,-1.436913e+11,0.000000e+00,0.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,-7.533332e+10,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000e+00,0.000000,0.000000e+00,-1.000000,-1.000000,0.000000,-1.395063e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,640.000000,3.455900e+04,8.000000e+01,6.000000,4.888600e+04,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,6.318762e-01,2.457425e+04,0.000000e+00,4.202525e+04,4.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,3.200000e+01,0.000000e+00,4.093266e-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,3.200000e+01,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000e+00,0.000000,0.000000e+00,31.000000,-1.000000,0.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1568.000000,4.322600e+04,4.430000e+02,6.000000,5.602255e+05,2.000000,1.000000e+00,3.100000e+01,2.600000e+01,3.100000e+01,0.000000,28.500000,0.000000,26.000000,0.000000,15.500000,0.000000,8.986458e+01,7.758975e+00,2.305935e+05,0.000000e+00,3.511780e+05,3.502000e+03,2.544285e+05,4.528030e+04,0.000000e+00,1.283895e+05,9.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,6.000000e+01,3.200000e+01,3.947342e+00,0.884223,0.000000,45.000000,35.333333,15.500000,240.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,50.000000,28.500000,15.500000,6.000000e+01,0.0,0.0,0.0,0.0,0.0,2.000000,3.100000e+01,1.000000,2.600000e+01,1505.000000,-1.000000,0.000000,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2718.000000,5.228300e+04,4.430000e+02,6.000000,1.076907e+07,5.000000,4.000000e+00,4.300000e+02,3.010000e+02,3.430000e+02,17.000000,54.250000,99.136270,238.750000,0.000000,150.750000,99.574634,2.373444e+03,6.327312e+01,2.127172e+06,1.534637e+06,1.003828e+07,1.644530e+05,5.399800e+06,1.842099e+06,1.809952e+05,4.536104e+06,4.263050e+04,2.624452e+05,4.186954e+04,4.414090e+04,1.498700e+05,6.000000e+00,0.000000,0.000000,0.000000,0.000000,1.360000e+02,1.120000e+02,3.198260e+01,16.817463,0.000000,549.000000,124.666667,216.526898,46856.028450,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.0,155.078462,54.250000,150.750000,1.360000e+02,0.0,0.0,0.0,0.0,0.0,5.000000,4.300000e+02,4.000000,3.010000e+02,65535.000000,349.000000,1.000000,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,14157.000000,1.045267e+06,1.328159e+06,442719.666667,1.199999e+08,27165.000000,1.319105e+06,9.043781e+06,8.050972e+07,1.072354e+06,1460.000000,1460.000000,1032.375901,1460.000000,1460.000000,1460.000000,321545.139706,1.705000e+08,2.000000e+06,1.199514e+08,8.447404e+07,1.199514e+08,1.199514e+08,1.199999e+08,1.199514e+08,8.478313e+07,1.199514e+08,1.199514e+08,1.199838e+08,1.192258e+08,8.467014e+07,1.198520e+08,1.192258e+08,680.714286,192.500000,876.000000,112.000000,1.858721e+10,3.546917e+10,2.000000e+06,500000.000000,32762.000000,1460.000000,1373.111111,842.931393,710533.333333,8760.000000,65535.000000,127.000000,1.000000,20.000000,1.000000,0.0,1812.000000,1460.000000,1460.000000,1.858721e+10,0.0,0.0,0.0,0.0,0.0,17877.000000,9.043781e+06,55652.000000,8.050972e+07,65535.000000,65535.000000,6335.000000,1.705248e+08,9.718488e+07,4.020815e+07,9.718488e+07,9.718488e+07,1.199514e+08,7.737303e+07,1.199514e+08,1.199514e+08

In [28]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355630 entries, 0 to 355629
Data columns (total 86 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   355630 non-null  int64
 1   Flow ID                      355629 non-null  object
 2   Source IP                    355630 non-null  object
 3   Source Port                  355630 non-null  int64
 4   Destination IP               355630 non-null  object
 5   Destination Port             355630 non-null  float64
 6   Protocol                     355630 non-null  float64
 7   Timestamp                    355630 non-null  object
 8   Flow Duration                355630 non-null  int64
 9   Total Fwd Packets            355630 non-null  int64
 10  Total Backward Packets       355630 non-null  int64
 11  Total Length of Fwd Packets  355630 non-null  float64
 12  Total Length of Bwd Packets  355630 non-null  float64
 13  Fwd Packet Length Max        355630 non-null  float64
 14  Fwd Packet Length Min        355630 non-null  float64
 15  Fwd Packet Length Mean       355630 non-null  float64
 16  Fwd Packet Length Std        355630 non-null  float64
 17  Bwd Packet Length Max        355630 non-null  float64
 18  Bwd Packet Length Min        355630 non-null  float64
 19  Bwd Packet Length Mean       355630 non-null  float64
 20  Bwd Packet Length Std        355630 non-null  float64
 21  Flow Bytes/s                 355630 non-null  float64
 22  Flow Packets/s               355630 non-null  float64
 23  Flow IAT Mean                355630 non-null  float64
 24  Flow IAT Std                 355630 non-null  float64
 25  Flow IAT Max                 355630 non-null  float64
 26  Flow IAT Min                 355630 non-null  float64
 27  Fwd IAT Total                355630 non-null  float64
 28  Fwd IAT Mean                 355630 non-null  float64
 29  Fwd IAT Std                  355630 non-null  float64
 30  Fwd IAT Max                  355630 non-null  float64
 31  Fwd IAT Min                  355630 non-null  float64
 32  Bwd IAT Total                355630 non-null  float64
 33  Bwd IAT Mean                 355630 non-null  float64
 34  Bwd IAT Std                  355630 non-null  float64
 35  Bwd IAT Max                  355630 non-null  float64
 36  Bwd IAT Min                  355630 non-null  float64
 37  Fwd PSH Flags                355630 non-null  float64
 38  Bwd PSH Flags                355630 non-null  float64
 39  Fwd URG Flags                355630 non-null  int64
 40  Bwd URG Flags                355630 non-null  int64
 41  Fwd Header Length            355630 non-null  int64
 42  Bwd Header Length            355630 non-null  int64
 43  Fwd Packets/s                355630 non-null  float64
 44  Bwd Packets/s                355629 non-null  float64
 45  Min Packet Length            355629 non-null  float64
 46  Max Packet Length            355629 non-null  float64
 47  Packet Length Mean           355629 non-null  float64
 48  Packet Length Std            355629 non-null  float64
 49  Packet Length Variance       355629 non-null  float64
 50  FIN Flag Count               355629 non-null  float64
 51  SYN Flag Count               355629 non-null  float64
 52  RST Flag Count               355629 non-null  float64
 53  PSH Flag Count               355629 non-null  float64
 54  ACK Flag Count               355629 non-null  float64
 55  URG Flag Count               355629 non-null  float64
 56  CWE Flag Count               355629 non-null  object
 57  ECE Flag Count               355628 non-null  float64
 58  Down/Up Ratio                355628 non-null  object
 59  Average Packet Size          355627 non-null  float64
 60  Avg Fwd Segment Size         355627 non-null  float64
 61  Avg Bwd Segment Size         355627 non-null  float64
 62  Fwd Header Length.1          355627 non-null  float64
 63  Fwd Avg Bytes/Bulk           355627 non-null  object
 64  Fwd Avg Packets/Bulk         355626 non-null  float64
 65  Fwd Avg Bulk Rate            355626 non-null  float64
 66  Bwd Avg Bytes/Bulk           355626 non-null  float64
 67  Bwd Avg Packets/Bulk         355626 non-null  float64
 68  Bwd Avg Bulk Rate            355626 non-null  float64
 69  Subflow Fwd Packets          355626 non-null  float64
 70  Subflow Fwd Bytes            355626 non-null  float64
 71  Subflow Bwd Packets          355626 non-null  float64
 72  Subflow Bwd Bytes            355626 non-null  float64
 73  Init_Win_bytes_forward       355626 non-null  float64
 74  Init_Win_bytes_backward      355626 non-null  float64
 75  act_data_pkt_fwd             355626 non-null  float64
 76  min_seg_size_forward         355626 non-null  float64
 77  Active Mean                  355626 non-null  float64
 78  Active Std                   355626 non-null  float64
 79  Active Max                   355626 non-null  float64
 80  Active Min                   355626 non-null  float64
 81  Idle Mean                    355626 non-null  float64
 82  Idle Std                     355626 non-null  float64
 83  Idle Max                     355626 non-null  float64
 84  Idle Min                     355626 non-null  float64
 85  Label                        355630 non-null  object
dtypes: float64(69), int64(9), object(8)
memory usage: 233.3+ MB

In [29]:
dataFrame["Label"].value_counts().to_dict()

{'Android_Adware': 147443,
 'Android_Scareware': 117082,
 'Android_SMS_Malware': 67397,
 'Benign': 23708}

### 2.4. Xử lý dữ liệu không toàn vẹn
Dữ liệu có 4 dòng bị thiếu giá trị (276556, 285435, 323136, 262292), có thể xử lý bằng cách bỏ đi các dòng này do số dòng bị thiếu ít.

In [30]:
null_positions = {
    col: dataFrame.index[dataFrame[col].isna()].tolist()
    for col in dataFrame.columns
    if dataFrame[col].isna().any()
}

for col, idx_list in null_positions.items():
    print(f"{col}: {idx_list}")

Flow ID: [276556]
Bwd Packets/s: [285435]
Min Packet Length: [285435]
Max Packet Length: [285435]
Packet Length Mean: [285435]
Packet Length Std: [285435]
Packet Length Variance: [285435]
FIN Flag Count: [285435]
SYN Flag Count: [285435]
RST Flag Count: [285435]
PSH Flag Count: [285435]
ACK Flag Count: [285435]
URG Flag Count: [285435]
CWE Flag Count: [285435]
ECE Flag Count: [285435, 323136]
Down/Up Ratio: [285435, 323136]
Average Packet Size: [276556, 285435, 323136]
Avg Fwd Segment Size: [276556, 285435, 323136]
Avg Bwd Segment Size: [276556, 285435, 323136]
Fwd Header Length.1: [276556, 285435, 323136]
Fwd Avg Bytes/Bulk: [276556, 285435, 323136]
Fwd Avg Packets/Bulk: [262292, 276556, 285435, 323136]
Fwd Avg Bulk Rate: [262292, 276556, 285435, 323136]
Bwd Avg Bytes/Bulk: [262292, 276556, 285435, 323136]
Bwd Avg Packets/Bulk: [262292, 276556, 285435, 323136]
Bwd Avg Bulk Rate: [262292, 276556, 285435, 323136]
Subflow Fwd Packets: [262292, 276556, 285435, 323136]
Subflow Fwd Bytes: [262292, 276556, 285435, 323136]
Subflow Bwd Packets: [262292, 276556, 285435, 323136]
Subflow Bwd Bytes: [262292, 276556, 285435, 323136]
Init_Win_bytes_forward: [262292, 276556, 285435, 323136]
Init_Win_bytes_backward: [262292, 276556, 285435, 323136]
act_data_pkt_fwd: [262292, 276556, 285435, 323136]
min_seg_size_forward: [262292, 276556, 285435, 323136]
Active Mean: [262292, 276556, 285435, 323136]
Active Std: [262292, 276556, 285435, 323136]
Active Max: [262292, 276556, 285435, 323136]
Active Min: [262292, 276556, 285435, 323136]
Idle Mean: [262292, 276556, 285435, 323136]
Idle Std: [262292, 276556, 285435, 323136]
Idle Max: [262292, 276556, 285435, 323136]
Idle Min: [262292, 276556, 285435, 323136]

In [31]:
print(dataFrame.loc[276556], "\n\n", dataFrame.loc[262292], "\n\n", dataFrame.loc[285435], "\n\n", dataFrame.loc[323136])

Unnamed: 0                                    2756
Flow ID                                        NaN
Source IP                                        0
Source Port                                      0
Destination IP                                   0
Destination Port                               0.0
Protocol                                       0.0
Timestamp                                        0
Flow Duration                                    0
Total Fwd Packets                                0
Total Backward Packets                           0
Total Length of Fwd Packets                    0.0
Total Length of Bwd Packets                    0.0
Fwd Packet Length Max                          0.0
Fwd Packet Length Min                         20.0
Fwd Packet Length Mean                        32.0
Fwd Packet Length Std                    31.460391
Bwd Packet Length Max                    31.460391
Bwd Packet Length Min                         38.0
Bwd Packet Length Mean                       166.0
Bwd Packet Length Std                    80.666667
Flow Bytes/s                             73.900834
Flow Packets/s                         5461.333333
Flow IAT Mean                                  0.0
Flow IAT Std                                   0.0
Flow IAT Max                                   0.0
Flow IAT Min                                   0.0
Fwd IAT Total                                  0.0
Fwd IAT Mean                                   0.0
Fwd IAT Std                                    0.0
Fwd IAT Max                                    0.0
Fwd IAT Min                                    1.0
Bwd IAT Total                                121.0
Bwd IAT Mean                                  38.0
Bwd IAT Std                                  166.0
Bwd IAT Max                                   20.0
Bwd IAT Min                                    0.0
Fwd PSH Flags                                  0.0
Bwd PSH Flags                                  0.0
Fwd URG Flags                                    0
Bwd URG Flags                                    0
Fwd Header Length                                0
Bwd Header Length                                1
Fwd Packets/s                                 38.0
Bwd Packets/s                                  1.0
Min Packet Length                            166.0
Max Packet Length                             -1.0
Packet Length Mean                            -1.0
Packet Length Std                              0.0
Packet Length Variance                        20.0
FIN Flag Count                                 0.0
SYN Flag Count                                 0.0
RST Flag Count                                 0.0
PSH Flag Count                                 0.0
ACK Flag Count                                 0.0
URG Flag Count                                 0.0
CWE Flag Count                                   0
ECE Flag Count                                 0.0
Down/Up Ratio                               BENIGN
Average Packet Size                            NaN
Avg Fwd Segment Size                           NaN
Avg Bwd Segment Size                           NaN
Fwd Header Length.1                            NaN
Fwd Avg Bytes/Bulk                             NaN
Fwd Avg Packets/Bulk                           NaN
Fwd Avg Bulk Rate                              NaN
Bwd Avg Bytes/Bulk                             NaN
Bwd Avg Packets/Bulk                           NaN
Bwd Avg Bulk Rate                              NaN
Subflow Fwd Packets                            NaN
Subflow Fwd Bytes                              NaN
Subflow Bwd Packets                            NaN
Subflow Bwd Bytes                              NaN
Init_Win_bytes_forward                         NaN
Init_Win_bytes_backward                        NaN
act_data_pkt_fwd                               NaN
min_seg_size_forward                           NaN
Active Mean                                    NaN
Active Std                                     NaN
Active Max                                     NaN
Active Min                                     NaN
Idle Mean                                      NaN
Idle Std                                       NaN
Idle Max                                       NaN
Idle Min                                       NaN
Label                          Android_SMS_Malware
Name: 276556, dtype: object

 Unnamed: 0                                  2557
Flow ID                                     6923
Source IP                       291380.770637023
Source Port                              1045267
Destination IP                                17
Destination Port                       1328159.0
Protocol                           442719.666667
Timestamp                       534188.743461834
Flow Duration                            1045267
Total Fwd Packets                          27165
Total Backward Packets                   1319105
Total Length of Fwd Packets        146567.222222
Total Length of Bwd Packets        355177.836427
Fwd Packet Length Max                  1072354.0
Fwd Packet Length Min                       17.0
Fwd Packet Length Mean                       0.0
Fwd Packet Length Std                        0.0
Bwd Packet Length Max                        0.0
Bwd Packet Length Min                        0.0
Bwd Packet Length Mean                     112.0
Bwd Packet Length Std                      224.0
Flow Bytes/s                            2.543463
Flow Packets/s                          6.358658
Flow IAT Mean                                0.0
Flow IAT Std                              1460.0
Flow IAT Max                          635.333333
Flow IAT Min                          723.472447
Fwd IAT Total                      523412.380952
Fwd IAT Mean                                 0.0
Fwd IAT Std                                  0.0
Fwd IAT Max                                  0.0
Fwd IAT Min                                  1.0
Bwd IAT Total                                0.0
Bwd IAT Mean                                 0.0
Bwd IAT Std                                  0.0
Bwd IAT Max                                  0.0
Bwd IAT Min                                  2.0
Fwd PSH Flags                         680.714286
Bwd PSH Flags                              192.5
Fwd URG Flags                                876
Bwd URG Flags                                112
Fwd Header Length                              0
Bwd Header Length                              0
Fwd Packets/s                                0.0
Bwd Packets/s                                0.0
Min Packet Length                            0.0
Max Packet Length                            0.0
Packet Length Mean                           4.0
Packet Length Std                          770.0
Packet Length Variance                      10.0
FIN Flag Count                            8760.0
SYN Flag Count                           65535.0
RST Flag Count                             127.0
PSH Flag Count                               1.0
ACK Flag Count                              20.0
URG Flag Count                               0.0
CWE Flag Count                                 0
ECE Flag Count                               0.0
Down/Up Ratio                                0.0
Average Packet Size                          0.0
Avg Fwd Segment Size                         0.0
Avg Bwd Segment Size                         0.0
Fwd Header Length.1                          0.0
Fwd Avg Bytes/Bulk                        BENIGN
Fwd Avg Packets/Bulk                         NaN
Fwd Avg Bulk Rate                            NaN
Bwd Avg Bytes/Bulk                           NaN
Bwd Avg Packets/Bulk                         NaN
Bwd Avg Bulk Rate                            NaN
Subflow Fwd Packets                          NaN
Subflow Fwd Bytes                            NaN
Subflow Bwd Packets                          NaN
Subflow Bwd Bytes                            NaN
Init_Win_bytes_forward                       NaN
Init_Win_bytes_backward                      NaN
act_data_pkt_fwd                             NaN
min_seg_size_forward                         NaN
Active Mean                                  NaN
Active Std                                   NaN
Active Max                                   NaN
Active Min                                   NaN
Idle Mean                                    NaN
Idle Std                                     NaN
Idle Max                                     NaN
Idle Min                                     NaN
Label                          Android_Scareware
Name: 262292, dtype: object

 Unnamed: 0                                                       3165
Flow ID                        172.217.10.238-10.42.0.151-443-50096-6
Source IP                                                 10.42.0.151
Source Port                                                     50096
Destination IP                                         172.217.10.238
Destination Port                                                443.0
Protocol                                                          6.0
Timestamp                                         30/06/2017 10:35:52
Flow Duration                                                   37222
Total Fwd Packets                                                   1
Total Backward Packets                                              1
Total Length of Fwd Packets                                       0.0
Total Length of Bwd Packets                                       0.0
Fwd Packet Length Max                                             0.0
Fwd Packet Length Min                                             0.0
Fwd Packet Length Mean                                            0.0
Fwd Packet Length Std                                             0.0
Bwd Packet Length Max                                             0.0
Bwd Packet Length Min                                             0.0
Bwd Packet Length Mean                                            0.0
Bwd Packet Length Std                                             0.0
Flow Bytes/s                                                      0.0
Flow Packets/s                                              53.731664
Flow IAT Mean                                                 37222.0
Flow IAT Std                                                      0.0
Flow IAT Max                                                  37222.0
Flow IAT Min                                                  37222.0
Fwd IAT Total                                                     0.0
Fwd IAT Mean                                                      0.0
Fwd IAT Std                                                       0.0
Fwd IAT Max                                                       0.0
Fwd IAT Min                                                       0.0
Bwd IAT Total                                                     0.0
Bwd IAT Mean                                                      0.0
Bwd IAT Std                                                       0.0
Bwd IAT Max                                                       0.0
Bwd IAT Min                                                       0.0
Fwd PSH Flags                                                     0.0
Bwd PSH Flags                                                     0.0
Fwd URG Flags                                                       0
Bwd URG Flags                                                       0
Fwd Header Length                                                  32
Bwd Header Length                                                  32
Fwd Packets/s                                               26.865832
Bwd Packets/s                                                     NaN
Min Packet Length                                                 NaN
Max Packet Length                                                 NaN
Packet Length Mean                                                NaN
Packet Length Std                                                 NaN
Packet Length Variance                                            NaN
FIN Flag Count                                                    NaN
SYN Flag Count                                                    NaN
RST Flag Count                                                    NaN
PSH Flag Count                                                    NaN
ACK Flag Count                                                    NaN
URG Flag Count                                                    NaN
CWE Flag Count                                                    NaN
ECE Flag Count                                                    NaN
Down/Up Ratio                                                     NaN
Average Packet Size                                               NaN
Avg Fwd Segment Size                                              NaN
Avg Bwd Segment Size                                              NaN
Fwd Header Length.1                                               NaN
Fwd Avg Bytes/Bulk                                                NaN
Fwd Avg Packets/Bulk                                              NaN
Fwd Avg Bulk Rate                                                 NaN
Bwd Avg Bytes/Bulk                                                NaN
Bwd Avg Packets/Bulk                                              NaN
Bwd Avg Bulk Rate                                                 NaN
Subflow Fwd Packets                                               NaN
Subflow Fwd Bytes                                                 NaN
Subflow Bwd Packets                                               NaN
Subflow Bwd Bytes                                                 NaN
Init_Win_bytes_forward                                            NaN
Init_Win_bytes_backward                                           NaN
act_data_pkt_fwd                                                  NaN
min_seg_size_forward                                              NaN
Active Mean                                                       NaN
Active Std                                                        NaN
Active Max                                                        NaN
Active Min                                                        NaN
Idle Mean                                                         NaN
Idle Std                                                          NaN
Idle Max                                                          NaN
Idle Min                                                          NaN
Label                                             Android_SMS_Malware
Name: 285435, dtype: object

 Unnamed: 0                                    2877
Flow ID                              7258830000000
Source IP                                      281
Source Port                                 124560
Destination IP                    17794.2857142857
Destination Port                      28844.347278
Protocol                                   65812.0
Timestamp                                        3
Flow Duration                                    0
Total Fwd Packets                                0
Total Backward Packets                           0
Total Length of Fwd Packets                    0.0
Total Length of Bwd Packets                  180.0
Fwd Packet Length Max                        168.0
Fwd Packet Length Min                     0.731181
Fwd Packet Length Mean                    0.731181
Fwd Packet Length Std                          0.0
Bwd Packet Length Max                       1460.0
Bwd Packet Length Min                   318.529412
Bwd Packet Length Mean                  567.049504
Bwd Packet Length Std                321545.139706
Flow Bytes/s                                   0.0
Flow Packets/s                                 0.0
Flow IAT Mean                                  0.0
Flow IAT Std                                   1.0
Flow IAT Max                                   0.0
Flow IAT Min                                   0.0
Fwd IAT Total                                  0.0
Fwd IAT Mean                                   0.0
Fwd IAT Std                                    1.0
Fwd IAT Max                               338.4375
Fwd IAT Min                                 43.125
Bwd IAT Total                               633.75
Bwd IAT Mean                                 180.0
Bwd IAT Std                                    0.0
Bwd IAT Max                                    0.0
Bwd IAT Min                                    0.0
Fwd PSH Flags                                  0.0
Bwd PSH Flags                                  0.0
Fwd URG Flags                                    0
Bwd URG Flags                                    8
Fwd Header Length                              345
Bwd Header Length                                8
Fwd Packets/s                               5070.0
Bwd Packets/s                              65535.0
Min Packet Length                          32762.0
Max Packet Length                              2.0
Packet Length Mean                            20.0
Packet Length Std                              0.0
Packet Length Variance                         0.0
FIN Flag Count                                 0.0
SYN Flag Count                                 0.0
RST Flag Count                                 0.0
PSH Flag Count                                 0.0
ACK Flag Count                                 0.0
URG Flag Count                                 0.0
CWE Flag Count                           SCAREWARE
ECE Flag Count                                 NaN
Down/Up Ratio                                  NaN
Average Packet Size                            NaN
Avg Fwd Segment Size                           NaN
Avg Bwd Segment Size                           NaN
Fwd Header Length.1                            NaN
Fwd Avg Bytes/Bulk                             NaN
Fwd Avg Packets/Bulk                           NaN
Fwd Avg Bulk Rate                              NaN
Bwd Avg Bytes/Bulk                             NaN
Bwd Avg Packets/Bulk                           NaN
Bwd Avg Bulk Rate                              NaN
Subflow Fwd Packets                            NaN
Subflow Fwd Bytes                              NaN
Subflow Bwd Packets                            NaN
Subflow Bwd Bytes                              NaN
Init_Win_bytes_forward                         NaN
Init_Win_bytes_backward                        NaN
act_data_pkt_fwd                               NaN
min_seg_size_forward                           NaN
Active Mean                                    NaN
Active Std                                     NaN
Active Max                                     NaN
Active Min                                     NaN
Idle Mean                                      NaN
Idle Std                                       NaN
Idle Max                                       NaN
Idle Min                                       NaN
Label                          Android_SMS_Malware
Name: 323136, dtype: object

In [32]:
dataFrame.notna().all().all()

np.False_

In [33]:
dataFrame = dataFrame.drop(index=[262292, 276556, 285435, 323136])

In [34]:
dataFrame.notna().all().all()

np.True_

### 2.5. Xử lý các cột không đúng kiểu dữ liệu
Có một số cột chứa nhiều giá trị số nguyên bị ép về kiểu số thập phân, cần biến đổi bằng cách ép lại về kiểu số nguyên.
Tuy nhiên, có một số cột (CWE Flag Count, Fwd Avg Bytes/Bulk) chỉ có phân phối 1 loại giá trị sau khi ép kiểu về,
có thể bỏ đi các cột này do dư thừa.

In [35]:
object_cols = dataFrame.select_dtypes(include="object")
object_cols.head()

,Flow ID,Source IP,Destination IP,Timestamp,CWE Flag Count,Down/Up Ratio,Fwd Avg Bytes/Bulk,Label
0,172.217.6.202-10.42.0.211-443-50004-6,10.42.0.211,172.217.6.202,13/06/2017 11:52:39,0,1.0,0,Android_Adware
1,172.217.6.202-10.42.0.211-443-35455-6,10.42.0.211,172.217.6.202,13/06/2017 11:52:39,0,1.0,0,Android_Adware
2,131.253.61.68-10.42.0.211-443-51775-6,10.42.0.211,131.253.61.68,13/06/2017 11:52:42,0,1.0,0,Android_Adware
3,131.253.61.68-10.42.0.211-443-51775-6,10.42.0.211,131.253.61.68,13/06/2017 11:52:43,0,0.0,0,Android_Adware
4,131.253.61.68-10.42.0.211-443-51776-6,10.42.0.211,131.253.61.68,13/06/2017 11:52:42,0,0.0,0,Android_Adware

In [36]:
dataFrame["CWE Flag Count"].value_counts().to_dict()

{'0': 352461, '0.0': 3165}

In [37]:
dataFrame["Fwd Avg Bytes/Bulk"].value_counts().to_dict()

{'0': 288232, '0.0': 67394}

In [38]:
dataFrame["Down/Up Ratio"].value_counts().to_dict()

{'0.0': 154385,
 '1.0': 151914,
 '0': 20399,
 '1': 16749,
 '2.0': 7858,
 '3.0': 1993,
 '2': 1121,
 '4.0': 436,
 '3': 377,
 '5.0': 123,
 '4': 79,
 '6.0': 42,
 '8.0': 36,
 '7.0': 31,
 '5': 23,
 '12.0': 12,
 '6': 12,
 '8': 8,
 '9.0': 7,
 '10.0': 7,
 '11.0': 5,
 '7': 4,
 '11': 2,
 '9': 1,
 '12': 1,
 '75.0': 1}

In [39]:
dataFrame = dataFrame.drop(columns=["CWE Flag Count", "Fwd Avg Bytes/Bulk"])
dataFrame["Down/Up Ratio"] = pd.to_numeric(dataFrame["Down/Up Ratio"], errors='coerce').astype(int) # ép về int

In [40]:
dataFrame["Down/Up Ratio"].value_counts().to_dict()

{0: 174784,
 1: 168663,
 2: 8979,
 3: 2370,
 4: 515,
 5: 146,
 6: 54,
 8: 44,
 7: 35,
 12: 13,
 9: 8,
 10: 7,
 11: 7,
 75: 1}

### 2.6. Xóa cột Flow ID
Cột này chỉ có giá trị định danh nên cần được xóa khỏi tập dữ liệu

In [41]:
dataFrame = dataFrame.drop(columns=["Flow ID"])

### 2.7. Xử lý các cột có tất cả các giá trị đều giống nhau
Loại bỏ các cột có giá trị giống nhau để tránh thừa thông tin không cần thiết

In [42]:
dataFrame = dataFrame.loc[:, dataFrame.nunique() > 1]
dataFrame.head()

,Unnamed: 0,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,10.42.0.211,50004,172.217.6.202,443.0,6.0,13/06/2017 11:52:39,37027,1,1,0.0,0.0,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,54.014638,3.702700e+04,0.000000e+00,37027.0,37027.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,32,32,27.007319,27.007319,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.0,1.0,1,0.000000,0.000,0.000000,32.0,1.0,0.0,1.0,0.0,2994.0,362.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
1,1,10.42.0.211,35455,172.217.6.202,443.0,6.0,13/06/2017 11:52:39,36653,1,1,0.0,0.0,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,54.565793,3.665300e+04,0.000000e+00,36653.0,36653.0,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,32,32,27.282896,27.282896,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.0,1.0,1,0.000000,0.000,0.000000,32.0,1.0,0.0,1.0,0.0,2860.0,362.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
2,2,10.42.0.211,51775,131.253.61.68,443.0,6.0,13/06/2017 11:52:42,534099,8,12,1011.0,11924.0,581.0,0.0,126.375,207.799311,1460.0,0.0,993.666667,656.474376,24218.356522,37.446241,2.811047e+04,4.314810e+04,158676.0,8.0,481340.0,6.876286e+04,6.237618e+04,158676.0,449.0,487990.0,44362.727273,86342.042540,217790.0,8.0,0.0,180,244,14.978496,22.467745,0.0,1460.0,615.952381,672.744786,452585.547619,0.0,0.0,1.0,0.0,0.0,1,646.750000,126.375,993.666667,180.0,8.0,1011.0,12.0,11924.0,65535.0,63441.0,3.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
3,3,10.42.0.211,51775,131.253.61.68,443.0,6.0,13/06/2017 11:52:43,9309,3,0,0.0,0.0,0.0,0.0,0.000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,322.268772,4.654500e+03,5.137131e+03,8287.0,1022.0,9309.0,4.654500e+03,5.137131e+03,8287.0,1022.0,0.0,0.000000,0.000000,0.0,0.0,0.0,60,0,322.268772,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.0,0.0,0,0.000000,0.000,0.000000,60.0,3.0,0.0,0.0,0.0,65535.0,-1.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
4,4,10.42.0.211,51776,131.253.61.68,443.0,6.0,13/06/2017 11:52:42,19890496,8,6,430.0,5679.0,218.0,0.0,53.750,99.538578,1460.0,0.0,946.500000,710.412204,307.131607,0.703854,1.530038e+06,5.377887e+06,19426714.0,7.0,19890496.0,2.841499e+06,7.314093e+06,19426714.0,639.0,410964.0,82192.800000,154845.683018,355945.0,7.0,0.0,180,124,0.402202,0.301652,0.0,1460.0,407.266667,626.958471,393076.923810,0.0,0.0,1.0,0.0,0.0,0,436.357143,53.750,946.500000,180.0,8.0,430.0,6.0,5679.0,65535.0,64022.0,2.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware

### 2.8. Kiểm tra dữ liệu trước khi xuất ra file
Kiểm tra dữ liệu sau khi xử lý, đồng thời xóa cột Unnamed : 0 do cột này không có giá trị phân tích

In [43]:
dataFrame = dataFrame.drop(columns=["Unnamed: 0"])

In [44]:
dataFrame.describe()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,355626.000000,355626.000000,355626.000000,3.556260e+05,355626.000000,355626.000000,3.556260e+05,3.556260e+05,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,355626.000000,3.556260e+05,3.556260e+05,3.556260e+05,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,355626.000000,3.556260e+05,355626.000000,3.556260e+05,355626.000000,3.556260e+05,355626.000000,355626.000000,355626.000000,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05,3.556260e+05
mean,39138.304382,5198.782415,8.335321,1.092987e+07,7.357412,10.494593,6.791997e+02,1.129421e+04,212.001524,12.520283,59.644118,79.526313,320.406978,23.057701,168.537248,123.481423,8.399002e+04,5.494626e+03,3.175841e+06,2.426832e+06,9.448630e+06,2.057905e+06,7.540020e+06,3.206522e+06,1.934147e+06,6.253339e+06,2.079854e+06,5.632490e+06,9.461668e+05,1.407311e+06,4.709314e+06,3.426236e+05,0.065442,-7.601343e+05,-1.580875e+06,4.685547e+03,814.702967,8.413744,374.616814,115.158944,144.896934,71484.728363,0.016669,0.065442,0.331337,0.430964,0.204122,0.556461,127.433405,59.644118,168.537248,-7.601343e+05,7.357412,6.791997e+02,10.494593,1.129421e+04,23386.883271,2032.585548,1.524405,-2.831850e+04,1.628143e+05,2.195225e+04,1.851564e+05,1.456534e+05,4.025724e+06,3.182527e+05,4.304876e+06,3.779037e+06
std,17866.230855,14350.915363,4.567164,2.180870e+07,67.005199,191.679025,1.941864e+04,2.763881e+05,366.936836,58.296582,119.309538,154.228963,540.177605,59.008405,311.333194,229.667556,9.112749e+05,3.913525e+04,8.459910e+06,6.202486e+06,1.829201e+07,7.922457e+06,1.843196e+07,8.859206e+06,6.110724e+06,1.447382e+07,8.166515e+06,1.816018e+07,4.583240e+06,5.227303e+06,1.517932e+07,3.750299e+06,0.247305,2.090467e+08,4.385679e+08,3.625932e+04,8590.264143,21.321284,563.917454,193.967289,224.699241,137222.148679,0.128029,0.247305,0.470695,0.495212,0.403059,0.635995,199.981517,119.309538,311.333194,2.090467e+08,67.005199,1.941864e+04,191.679025,2.763881e+05,30744.982569,8532.735513,14.938322,5.543875e+06,8.817765e+05,2.860244e+05,1.019477e+06,8.423659e+05,1.441518e+07,2.882901e+06,1.514008e+07,1.407042e+07
min,0.000000,0.000000,0.000000,-1.000000e+00,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,-2.000000e+06,-1.000000e+00,0.000000e+00,-1.000000e+00,-4.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,-7.533332e+10,-1.436913e+11,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.533332e+10,1.000000,0.000000e+00,0.000000,0.000000e+00,-1.000000,-1.000000,0.000000,-1.395063e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,34559.000000,80.000000,6.000000,4.888625e+04,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,6.318762e-01,2.457518e+04,0.000000e+00,4.202950e+04,4.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,3.200000e+01,0.000000e+00,4.093266e-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.200000e+01,1.000000,0.000000e+00,0.000000,0.000000e+00,31.000000,-1.000000,0.000000,2.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,43226.000000,443.000000,6.000000,5.602320e+05,2.000000,1.000000,3.100000e+01,2.600000e+01,31.000000,0.000000,28.500000,0.000000,26.000000,0.000000,15.500000,0.000000,8.987556e+01,7.758975e+00,2.306010e+05,0.000000e+00,3.512285e+05,3.502000e+03,2.544330e+05,4.528250e+04,0.000000e+00,1.283990e+05,9.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,6.000000e+01,3.200000e+01,3.947291e+00,0.884160,0.000000,45.000000,35.333333,15.500000,240.250000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,50.000000,28.500000,15.500000,6.000000e+01,2.000000,3.100000e+01,1.000000,2.600000e+01,1505.000000,-1.000000,0.000000,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,52283.000000,443.000000,6.000000,1.076925e+07,5.000000,4.000000,4.300000e+02,3.010000e+02,343.000000,16.750000,54.250000,99.136270,238.750000,0.000000,150.750000,99.549979,2.373513e+03,6.327312e+01,2.127183e+06,1.534653e+06,1.003829e+07,1.644655e+05,5.399878e+06,1.842149e+06,1.809968e+05,4.536146e+06,4.263100e+04,2.624470e+05,4.187293e+04,4.414165e+04,1.498805e+05,6.000000e+00,0.000000,1.360000e+02,1.120000e+02,3.198235e+01,16.817322,0.000000,549.000000,124.666667,216.510807,46876.930189,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,155.079231,54.250000,150.750000,1.360000e+02,5.000000,4.300000e+02,4.000000,3.010000e+02,65535.000000,349.000000,1.000000,3.200000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,65531.000000,65428.000000,17.000000,1.199999e+08,17877.000000,55652.000000,9.043781e+06,8.050972e+07,1460.000000,1460.000000,1460.000000,1032.375901,1460.000000,1460.000000,1460.000000,1002.677416,1.705000e+08,2.000000e+06,1.199514e+08,8.447404e+07,1.199514e+08,1.199514e+08,1.199999e+08,1.199514e+08,8.478313e+07,1.199514e+08,1.199514e+08,1.199838e+08,1.192258e+08,8.467014e+07,1.198520e+08,1.192258e+08,1.000000,1.858721e+10,3.546917e+10,2.000000e+06,500000.000000,1208.000000,1460.000000,1373.111111,842.931393,710533.333333,1.000000,1.000000,1.000000,1.000000,1.000000,75.000000,1812.000000,1460.000000,1460.000000,1.858721e+10,17877.000000,9.043781e+06,55652.000000,8.050972e+07,65535.000000,65535.000000,6335.000000,1.705248e+08,9.718488e+07,4.020815e+07,9.718488e+07,9.718488e+07,1.199514e+08,7.737303e+07,1.199514e+08,1.199514e+08

In [45]:
print("Is not null:", dataFrame.notna().all().all()) # Kiểm tra null trước khi lưu dữ liệu

Is not null: True

### 2.9. Lưu tập dữ liệu dưới dạng file parquet

In [46]:
dataFrame.to_parquet("../data_processed/cleaned_data.parquet")

# **Kết thúc**